install:
- ps: |
    Write-Host "Installing NUnit 3.8.0..." -ForegroundColor Cyan -NoNewline
    $toolsPath = "$env:SYSTEMDRIVE\Tools"
    $nunitPath = "$env:SYSTEMDRIVE\Tools\NUnit3"
    Remove-Item $nunitPath -Recurse -Force
    $zipPath = "$($env:TEMP)\NUnit.Console-3.8.0.zip"
    (New-Object Net.WebClient).DownloadFile('https://github.com/nunit/nunit-console/releases/download/3.8/NUnit.Console-3.8.0.zip', $zipPath)
    7z x $zipPath -y -o"$nunitPath" | Out-Null
    del $zipPath
    $zipPath = "$($env:TEMP)\Appveyor.NUnit3Logger.zip"
    (New-Object Net.WebClient).DownloadFile('https://www.appveyor.com/downloads/Appveyor.NUnit3Logger.zip', $zipPath)
    7z x $zipPath -y -o"$nunitPath\addins" | Out-Null
    Move-Item "$nunitPath\addins\appveyor.addins" "$nunitPath\appveyor.addins"
    del $zipPath
    Remove-Path "$nunitPath\bin"
    Add-Path "$nunitPath"
    Write-Host "NUnit 3.8.0 installed" -ForegroundColor Green

before_build:
  - nuget restore

build:
  verbosity: minimal
